import { type IconType } from 'svelte-icons-pack';

export const FcGoogle: IconType = {
  a: { viewBox: '0 0 48 48' },
  c: '<path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"/><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"/><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"/><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"/>',
};

export const CIRCLE_FLAGS_URL = 'https://hatscripts.github.io/circle-flags';
export const CIRCLE_FLAG_CODES = {
  Andorra: 'flags/ad.svg',
  'United Arab Emirates': 'flags/ae.svg',
  Afghanistan: 'flags/af.svg',
  'Antigua and Barbuda': 'flags/ag.svg',
  Anguilla: 'flags/ai.svg',
  Albania: 'flags/al.svg',
  Armenia: 'flags/am.svg',
  'Netherlands Antilles': 'flags/an.svg',
  Angola: 'flags/ao.svg',
  Antarctica: 'flags/aq.svg',
  Argentina: 'flags/ar.svg',
  'American Samoa': 'flags/as.svg',
  Austria: 'flags/at.svg',
  Australia: 'flags/au.svg',
  'Australian Capital Territory': 'flags/au-act.svg',
  'New South Wales': 'flags/au-nsw.svg',
  'Northern Territory': 'flags/au-nt.svg',
  Queensland: 'flags/au-qld.svg',
  'South Australia': 'flags/au-sa.svg',
  Tasmania: 'flags/au-tas.svg',
  Victoria: 'flags/au-vic.svg',
  'Western Australia': 'flags/au-wa.svg',
  Aruba: 'flags/aw.svg',
  'Åland Islands': 'flags/ax.svg',
  Azerbaijan: 'flags/az.svg',
  'Bosnia and Herzegovina': 'flags/ba.svg',
  Barbados: 'flags/bb.svg',
  Bangladesh: 'flags/bd.svg',
  Belgium: 'flags/be.svg',
  'Burkina Faso': 'flags/bf.svg',
  Bulgaria: 'flags/bg.svg',
  Bahrain: 'flags/bh.svg',
  Burundi: 'flags/bi.svg',
  Benin: 'flags/bj.svg',
  'Saint Barthélemy': 'flags/bl.svg',
  Bermuda: 'flags/bm.svg',
  Brunei: 'flags/bn.svg',
  Bolivia: 'flags/bo.svg',
  Bonaire: 'flags/bq-bo.svg',
  Saba: 'flags/bq-sa.svg',
  'Sint Eustatius': 'flags/bq-se.svg',
  Brazil: 'flags/br.svg',
  Bahamas: 'flags/bs.svg',
  Bhutan: 'flags/bt.svg',
  'Bouvet Island': 'flags/bv.svg',
  Botswana: 'flags/bw.svg',
  Belarus: 'flags/by.svg',
  Belize: 'flags/bz.svg',
  Canada: 'flags/ca.svg',
  'British Columbia': 'flags/ca-bc.svg',
  Quebec: 'flags/ca-qc.svg',
  Cocos: 'flags/cc.svg',
  'Congo, Democratic Republic of the': 'flags/cd.svg',
  'Central African Republic': 'flags/cf.svg',
  Congo: 'flags/cg.svg',
  Switzerland: 'flags/ch.svg',
  Grisons: 'flags/ch-gr.svg',
  'Ivory Coast': 'flags/ci.svg',
  'Cook Islands': 'flags/ck.svg',
  Chile: 'flags/cl.svg',
  Cameroon: 'flags/cm.svg',
  China: 'flags/cn.svg',
  Xinjiang: 'flags/cn-xj.svg',
  Colombia: 'flags/co.svg',
  Sark: 'flags/cq.svg',
  'Costa Rica': 'flags/cr.svg',
  Cuba: 'flags/cu.svg',
  'Cabo Verde': 'flags/cv.svg',
  Curaçao: 'flags/cw.svg',
  'Christmas Island': 'flags/cx.svg',
  Cyprus: 'flags/cy.svg',
  Czechia: 'flags/cz.svg',
  Germany: 'flags/de.svg',
  Djibouti: 'flags/dj.svg',
  Denmark: 'flags/dk.svg',
  Dominica: 'flags/dm.svg',
  'Dominican Republic': 'flags/do.svg',
  Algeria: 'flags/dz.svg',
  Ecuador: 'flags/ec.svg',
  Galápagos: 'flags/ec-w.svg',
  Estonia: 'flags/ee.svg',
  Egypt: 'flags/eg.svg',
  'Western Sahara': 'flags/eh.svg',
  Eritrea: 'flags/er.svg',
  Spain: 'flags/es.svg',
  Aragon: 'flags/es-ar.svg',
  Ceuta: 'flags/es-ce.svg',
  'Canary Islands': 'flags/es-cn.svg',
  Catalonia: 'flags/es-ct.svg',
  Galicia: 'flags/es-ga.svg',
  'Balearic Islands': 'flags/es-ib.svg',
  Melilla: 'flags/es-ml.svg',
  'Basque Country': 'flags/es-pv.svg',
  Ethiopia: 'flags/et.svg',
  Afar: 'flags/et-af.svg',
  Amhara: 'flags/et-am.svg',
  'Benishangul-Gumuz': 'flags/et-be.svg',
  Gambela: 'flags/et-ga.svg',
  Harari: 'flags/et-ha.svg',
  Oromia: 'flags/et-or.svg',
  Sidama: 'flags/et-si.svg',
  "Southern Nations, Nationalities, and Peoples' Region": 'flags/et-sn.svg',
  Somali: 'flags/et-so.svg',
  'South West Region': 'flags/et-sw.svg',
  Tigray: 'flags/et-ti.svg',
  'European Union': 'flags/european_union.svg',
  Finland: 'flags/fi.svg',
  Fiji: 'flags/fj.svg',
  'Falkland Islands': 'flags/fk.svg',
  Micronesia: 'flags/fm.svg',
  'Faroe Islands': 'flags/fo.svg',
  France: 'flags/fr.svg',
  Corsica: 'flags/fr-20r.svg',
  Brittany: 'flags/fr-bre.svg',
  'Clipperton Island': 'flags/fr-cp.svg',
  Gabon: 'flags/ga.svg',
  'United Kingdom': 'flags/gb.svg',
  Cornwall: 'flags/gb-con.svg',
  England: 'flags/gb-eng.svg',
  'Northern Ireland': 'flags/gb-nir.svg',
  Orkney: 'flags/gb-ork.svg',
  Scotland: 'flags/gb-sct.svg',
  Wales: 'flags/gb-wls.svg',
  Grenada: 'flags/gd.svg',
  Georgia: 'flags/us-ga.svg',
  Abkhazia: 'flags/ge-ab.svg',
  'French Guiana': 'flags/gf.svg',
  Guernsey: 'flags/gg.svg',
  Ghana: 'flags/gh.svg',
  Gibraltar: 'flags/gi.svg',
  Greenland: 'flags/gl.svg',
  Gambia: 'flags/gm.svg',
  Guinea: 'flags/gn.svg',
  Guadeloupe: 'flags/gp.svg',
  'Equatorial Guinea': 'flags/gq.svg',
  Greece: 'flags/gr.svg',
  'South Georgia and the South Sandwich Islands': 'flags/gs.svg',
  Guatemala: 'flags/gt.svg',
  Guam: 'flags/gu.svg',
  'Guinea-Bissau': 'flags/gw.svg',
  Guyana: 'flags/gy.svg',
  'Hong Kong': 'flags/hk.svg',
  'Heard Island and McDonald Islands': 'flags/hm.svg',
  Honduras: 'flags/hn.svg',
  Croatia: 'flags/hr.svg',
  Haiti: 'flags/ht.svg',
  Hungary: 'flags/hu.svg',
  Indonesia: 'flags/id.svg',
  'West Java': 'flags/id-jb.svg',
  'Central Java': 'flags/id-jt.svg',
  Ireland: 'flags/ie.svg',
  Israel: 'flags/il.svg',
  'Isle of Man': 'flags/im.svg',
  India: 'flags/in.svg',
  Assam: 'flags/in-as.svg',
  Gujarat: 'flags/in-gj.svg',
  Karnataka: 'flags/in-ka.svg',
  Manipur: 'flags/in-mn.svg',
  Mizoram: 'flags/in-mz.svg',
  Odisha: 'flags/in-or.svg',
  Telangana: 'flags/in-tg.svg',
  'Tamil Nadu': 'flags/in-tn.svg',
  'British Indian Ocean Territory': 'flags/io.svg',
  Iraq: 'flags/iq.svg',
  Kurdistan: 'flags/iq-kr.svg',
  Iran: 'flags/ir.svg',
  Iceland: 'flags/is.svg',
  Italy: 'flags/it.svg',
  Piedmont: 'flags/it-21.svg',
  'Aosta Valley': 'flags/it-23.svg',
  Lombardy: 'flags/it-25.svg',
  'Trentino-Alto Adige': 'flags/it-32.svg',
  Veneto: 'flags/it-34.svg',
  'Friuli Venezia Giulia': 'flags/it-36.svg',
  Liguria: 'flags/it-42.svg',
  'Emilia-Romagna': 'flags/it-45.svg',
  Tuscany: 'flags/it-52.svg',
  Umbria: 'flags/it-55.svg',
  Marche: 'flags/it-57.svg',
  Lazio: 'flags/it-62.svg',
  Abruzzo: 'flags/it-65.svg',
  Molise: 'flags/it-67.svg',
  Campania: 'flags/it-72.svg',
  Apulia: 'flags/it-75.svg',
  Basilicata: 'flags/it-77.svg',
  Calabria: 'flags/it-78.svg',
  Sicily: 'flags/it-82.svg',
  Sardinia: 'flags/it-88.svg',
  Jersey: 'flags/je.svg',
  Jamaica: 'flags/jm.svg',
  Jordan: 'flags/jo.svg',
  Japan: 'flags/jp.svg',
  Kenya: 'flags/ke.svg',
  Kyrgyzstan: 'flags/kg.svg',
  Cambodia: 'flags/kh.svg',
  Kiribati: 'flags/ki.svg',
  Comoros: 'flags/km.svg',
  'Saint Kitts and Nevis': 'flags/kn.svg',
  'North Korea': 'flags/kp.svg',
  'South Korea': 'flags/kr.svg',
  Kuwait: 'flags/kw.svg',
  'Cayman Islands': 'flags/ky.svg',
  Kazakhstan: 'flags/kz.svg',
  Laos: 'flags/la.svg',
  Lebanon: 'flags/lb.svg',
  'Saint Lucia': 'flags/lc.svg',
  Liechtenstein: 'flags/li.svg',
  'Sri Lanka': 'flags/lk.svg',
  Liberia: 'flags/lr.svg',
  Lesotho: 'flags/ls.svg',
  Lithuania: 'flags/lt.svg',
  Luxembourg: 'flags/lu.svg',
  Latvia: 'flags/lv.svg',
  Libya: 'flags/ly.svg',
  Morocco: 'flags/ma.svg',
  Mars: 'flags/mars.svg',
  Monaco: 'flags/mc.svg',
  Moldova: 'flags/md.svg',
  Montenegro: 'flags/me.svg',
  'Saint-Martin': 'flags/mf.svg',
  Madagascar: 'flags/mg.svg',
  'Marshall Islands': 'flags/mh.svg',
  'North Macedonia': 'flags/mk.svg',
  Mali: 'flags/ml.svg',
  Myanmar: 'flags/mm.svg',
  Mongolia: 'flags/mn.svg',
  Macao: 'flags/mo.svg',
  'Northern Mariana Islands': 'flags/mp.svg',
  Martinique: 'flags/mq.svg',
  Mauritania: 'flags/mr.svg',
  Montserrat: 'flags/ms.svg',
  Malta: 'flags/mt.svg',
  Mauritius: 'flags/mu.svg',
  Maldives: 'flags/mv.svg',
  Malawi: 'flags/mw.svg',
  Mexico: 'flags/mx.svg',
  Malaysia: 'flags/my.svg',
  Mozambique: 'flags/mz.svg',
  Namibia: 'flags/na.svg',
  'New Caledonia': 'flags/nc.svg',
  Niger: 'flags/ne.svg',
  'Norfolk Island': 'flags/nf.svg',
  Nigeria: 'flags/ng.svg',
  Nicaragua: 'flags/ni.svg',
  Netherlands: 'flags/nl.svg',
  Friesland: 'flags/nl-fr.svg',
  Norway: 'flags/no.svg',
  Nepal: 'flags/np.svg',
  Nauru: 'flags/nr.svg',
  Niue: 'flags/nu.svg',
  'New Zealand': 'flags/nz.svg',
  Oman: 'flags/om.svg',
  Panama: 'flags/pa.svg',
  Peru: 'flags/pe.svg',
  'French Polynesia': 'flags/pf.svg',
  'Papua New Guinea': 'flags/pg.svg',
  Philippines: 'flags/ph.svg',
  Pakistan: 'flags/pk.svg',
  'Azad Kashmir': 'flags/pk-jk.svg',
  Sindh: 'flags/pk-sd.svg',
  Poland: 'flags/pl.svg',
  'Saint Pierre and Miquelon': 'flags/pm.svg',
  'Pitcairn Islands': 'flags/pn.svg',
  'Puerto Rico': 'flags/pr.svg',
  Palestine: 'flags/ps.svg',
  Azores: 'flags/pt-20.svg',
  Madeira: 'flags/pt-30.svg',
  Portugal: 'flags/pt.svg',
  Palau: 'flags/pw.svg',
  Paraguay: 'flags/py.svg',
  Qatar: 'flags/qa.svg',
  Réunion: 'flags/re.svg',
  Romania: 'flags/ro.svg',
  Serbia: 'flags/rs.svg',
  Russia: 'flags/ru.svg',
  Bashkortostan: 'flags/ru-ba.svg',
  Chechnya: 'flags/ru-ce.svg',
  Chuvashia: 'flags/ru-cu.svg',
  Dagestan: 'flags/ru-da.svg',
  "Donetsk People's Republic": 'flags/ru-dpr.svg',
  'Komi Republic': 'flags/ru-ko.svg',
  "Luhansk People's Republic": 'flags/ru-lpr.svg',
  Tatarstan: 'flags/ru-ta.svg',
  Udmurtia: 'flags/ru-ud.svg',
  Rwanda: 'flags/rw.svg',
  'Saudi Arabia': 'flags/sa.svg',
  'Solomon Islands': 'flags/sb.svg',
  Seychelles: 'flags/sc.svg',
  Sudan: 'flags/sd.svg',
  Sweden: 'flags/se.svg',
  Singapore: 'flags/sg.svg',
  'Ascension Island': 'flags/sh-ac.svg',
  'Saint Helena': 'flags/sh-hl.svg',
  'Tristan da Cunha': 'flags/sh-ta.svg',
  Slovenia: 'flags/si.svg',
  'Svalbard and Jan Mayen': 'flags/sj.svg',
  Slovakia: 'flags/sk.svg',
  'Sierra Leone': 'flags/sl.svg',
  'San Marino': 'flags/sm.svg',
  Senegal: 'flags/sn.svg',
  Somalia: 'flags/so.svg',
  'Soviet Union': 'flags/soviet_union.svg',
  Suriname: 'flags/sr.svg',
  'South Sudan': 'flags/ss.svg',
  'São Tomé and Príncipe': 'flags/st.svg',
  'El Salvador': 'flags/sv.svg',
  'Sint Maarten': 'flags/sx.svg',
  Syria: 'flags/sy.svg',
  Eswatini: 'flags/sz.svg',
  'Turks and Caicos Islands': 'flags/tc.svg',
  Chad: 'flags/td.svg',
  'French Southern Territories': 'flags/tf.svg',
  Togo: 'flags/tg.svg',
  Thailand: 'flags/th.svg',
  Tajikistan: 'flags/tj.svg',
  Tokelau: 'flags/tk.svg',
  'Timor-Leste': 'flags/tl.svg',
  Turkmenistan: 'flags/tm.svg',
  Tunisia: 'flags/tn.svg',
  Tonga: 'flags/to.svg',
  Turkey: 'flags/tr.svg',
  'Trinidad and Tobago': 'flags/tt.svg',
  Tuvalu: 'flags/tv.svg',
  Taiwan: 'flags/tw.svg',
  Tanzania: 'flags/tz.svg',
  Ukraine: 'flags/ua.svg',
  Uganda: 'flags/ug.svg',
  'United Nations': 'flags/other/united_nations.svg',
  'United States of America': 'flags/us.svg',
  Alaska: 'flags/us-ak.svg',
  Alabama: 'flags/us-al.svg',
  Arkansas: 'flags/us-ar.svg',
  Arizona: 'flags/us-az.svg',
  California: 'flags/us-ca.svg',
  Colorado: 'flags/us-co.svg',
  'District of Columbia': 'flags/us-dc.svg',
  Florida: 'flags/us-fl.svg',
  Hawaii: 'flags/us-hi.svg',
  Indiana: 'flags/us-in.svg',
  Maryland: 'flags/us-md.svg',
  Missouri: 'flags/us-mo.svg',
  Mississippi: 'flags/us-ms.svg',
  'North Carolina': 'flags/us-nc.svg',
  'New Mexico': 'flags/us-nm.svg',
  Oregon: 'flags/us-or.svg',
  'Rhode Island': 'flags/us-ri.svg',
  'South Carolina': 'flags/us-sc.svg',
  Tennessee: 'flags/us-tn.svg',
  Texas: 'flags/us-tx.svg',
  Washington: 'flags/us-wa.svg',
  Wisconsin: 'flags/us-wi.svg',
  Wyoming: 'flags/us-wy.svg',
  'United States Minor Outlying Islands': 'flags/um.svg',
  Uruguay: 'flags/uy.svg',
  Uzbekistan: 'flags/uz.svg',
  'Holy See': 'flags/va.svg',
  'Saint Vincent and the Grenadines': 'flags/vc.svg',
  Venezuela: 'flags/ve.svg',
  'Virgin Islands': 'flags/vi.svg',
  Vietnam: 'flags/vn.svg',
  Vanuatu: 'flags/vu.svg',
  'Wallis and Futuna': 'flags/wf.svg',
  Samoa: 'flags/ws.svg',
  Kosovo: 'flags/xk.svg',
  Yemen: 'flags/ye.svg',
  Mayotte: 'flags/yt.svg',
  Yugoslavia: 'flags/yu.svg',
  'South Africa': 'flags/za.svg',
  Zambia: 'flags/zm.svg',
  Zimbabwe: 'flags/zw.svg',
};
