import type { WidgetJoinMetricsPreview } from './server/db/schema';
import { CIRCLE_FLAG_ICONS, FLAT_COLOR_ICONS, VSCODE_ICONS } from './icons';

// Collection of mock widgets for demonstration purposes
export const mockWidgets: WidgetJoinMetricsPreview[] = [
  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        value: 13,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Janapese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        value: 34,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
      {
        name: 'all time',
        value: 953,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        value: 32,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4f8bce',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        value: 347,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#9450ce',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        value: 7,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  // ------------------------------------------------------------------

  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        value: 13,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Janapese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        value: 34,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
      {
        name: 'all time',
        value: 953,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        value: 32,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4f8bce',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        value: 347,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#9450ce',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        value: 7,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  // ------------------------------------------------------------------

  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        value: 13,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Janapese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        value: 34,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
      {
        name: 'all time',
        value: 953,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        value: 32,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4f8bce',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        value: 347,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#9450ce',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        value: 7,
        calculationType: 'day',
        valueDecimalPrecision: 0,
        order: 1,
      },
    ],
  },
];
