import { CIRCLE_FLAG_ICONS, FLAT_COLOR_ICONS, VSCODE_ICONS } from './icons';
import type { WidgetJoinMetricsData } from './server/services/metrics/types';

// Collection of mock widgets for demonstration purposes
export const mockWidgets: WidgetJoinMetricsData[] = [
  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        style: 'metric-trend',
        data: {
          value: 13,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Japanese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        style: 'metric-trend',
        data: {
          value: 34,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
      {
        name: 'all time',
        style: 'metric-trend',
        data: {
          value: 953,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        style: 'metric-trend',
        data: {
          value: 32,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4f8bce',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        style: 'metric-trend',
        data: {
          value: 347,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: true,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#9450ce',
    backgroundColor: '#ffffff',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        style: 'metric-trend',
        data: {
          value: 7,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  // ------------------------------------------------------------------

  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        style: 'metric-trend',
        data: {
          value: 13,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Japanese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        style: 'metric-trend',
        data: {
          value: 34,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
      {
        name: 'all time',
        style: 'metric-trend',
        data: {
          value: 953,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4fc59e',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        style: 'metric-trend',
        data: {
          value: 32,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#4f8bce',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        style: 'metric-trend',
        data: {
          value: 347,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#000000',
    accentColor: '#9450ce',
    backgroundColor: '#eaeaea',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        style: 'metric-trend',
        data: {
          value: 7,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  // ------------------------------------------------------------------

  {
    title: 'Projects Completed',
    subtitle: 'React Web Development',
    textIcon: null,
    imageUrl: VSCODE_ICONS.file_type_reactjs,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'completed',
        style: 'metric-trend',
        data: {
          value: 13,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Hours Learning Japanese',
    subtitle: 'Journey to fluency',
    textIcon: null,
    imageUrl: CIRCLE_FLAG_ICONS.Japan,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'this week',
        style: 'metric-trend',
        data: {
          value: 34,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
      {
        name: 'all time',
        style: 'metric-trend',
        data: {
          value: 953,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 2,
      },
    ],
  },

  {
    title: 'Publications',
    subtitle: 'ML research',
    textIcon: null,
    imageUrl: FLAT_COLOR_ICONS.fine_print,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4fc59e',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'articles',
        style: 'metric-trend',
        data: {
          value: 32,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'Open Source Contributions',
    subtitle: 'Community collaboration',
    textIcon: 'OS',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#4f8bce',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'contributions',
        style: 'metric-trend',
        data: {
          value: 347,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },

  {
    title: 'UI/UX Design',
    subtitle: 'User experience expertise',
    textIcon: 'UX',
    imageUrl: null,
    imagePlacement: 'left',
    padding: 13,
    border: false,
    borderWidth: 1,
    borderRadius: 6,
    color: '#ffffff',
    accentColor: '#9450ce',
    backgroundColor: '#333333',
    watermark: false,
    metrics: [
      {
        name: 'Design System',
        style: 'metric-trend',
        data: {
          value: 7,
        },
        period: 'day',
        valueDisplayPrecision: 0,
        valuePercent: false,
        order: 1,
      },
    ],
  },
];
